// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// generate_panel_data
arma::mat generate_panel_data(int N, int tt, double beta, double sigma);
RcppExport SEXP _HomogeneityTest_generate_panel_data(SEXP NSEXP, SEXP ttSEXP, SEXP betaSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type tt(ttSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_panel_data(N, tt, beta, sigma));
    return rcpp_result_gen;
END_RCPP
}
// probit_mle
arma::vec probit_mle(const arma::mat& X, const arma::vec& Y, int max_iter, double tol);
RcppExport SEXP _HomogeneityTest_probit_mle(SEXP XSEXP, SEXP YSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(probit_mle(X, Y, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// binary_individual_slopes
arma::vec binary_individual_slopes(const arma::mat& data, int max_iter, double tol);
RcppExport SEXP _HomogeneityTest_binary_individual_slopes(SEXP dataSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(binary_individual_slopes(data, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// param_bootstrap_data
arma::mat param_bootstrap_data(const arma::mat& data, const arma::vec& beta);
RcppExport SEXP _HomogeneityTest_param_bootstrap_data(SEXP dataSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(param_bootstrap_data(data, beta));
    return rcpp_result_gen;
END_RCPP
}
// quantile_func
double quantile_func(arma::vec vec, double prob);
RcppExport SEXP _HomogeneityTest_quantile_func(SEXP vecSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< double >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(quantile_func(vec, prob));
    return rcpp_result_gen;
END_RCPP
}
// boot_function
arma::vec boot_function(const arma::mat& data, int B, const arma::vec& null_model);
RcppExport SEXP _HomogeneityTest_boot_function(SEXP dataSEXP, SEXP BSEXP, SEXP null_modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type null_model(null_modelSEXP);
    rcpp_result_gen = Rcpp::wrap(boot_function(data, B, null_model));
    return rcpp_result_gen;
END_RCPP
}
// bootstrap_procedure
Rcpp::List bootstrap_procedure(const arma::mat& data, int B, int max_iter, double tol);
RcppExport SEXP _HomogeneityTest_bootstrap_procedure(SEXP dataSEXP, SEXP BSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_procedure(data, B, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// simulation_procedure
Rcpp::List simulation_procedure(int N, int tt, int no_sim, int B, int max_iter, double tol);
RcppExport SEXP _HomogeneityTest_simulation_procedure(SEXP NSEXP, SEXP ttSEXP, SEXP no_simSEXP, SEXP BSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type tt(ttSEXP);
    Rcpp::traits::input_parameter< int >::type no_sim(no_simSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(simulation_procedure(N, tt, no_sim, B, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HomogeneityTest_generate_panel_data", (DL_FUNC) &_HomogeneityTest_generate_panel_data, 4},
    {"_HomogeneityTest_probit_mle", (DL_FUNC) &_HomogeneityTest_probit_mle, 4},
    {"_HomogeneityTest_binary_individual_slopes", (DL_FUNC) &_HomogeneityTest_binary_individual_slopes, 3},
    {"_HomogeneityTest_param_bootstrap_data", (DL_FUNC) &_HomogeneityTest_param_bootstrap_data, 2},
    {"_HomogeneityTest_quantile_func", (DL_FUNC) &_HomogeneityTest_quantile_func, 2},
    {"_HomogeneityTest_boot_function", (DL_FUNC) &_HomogeneityTest_boot_function, 3},
    {"_HomogeneityTest_bootstrap_procedure", (DL_FUNC) &_HomogeneityTest_bootstrap_procedure, 4},
    {"_HomogeneityTest_simulation_procedure", (DL_FUNC) &_HomogeneityTest_simulation_procedure, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_HomogeneityTest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
