# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generate_panel_data <- function(N, tt, beta, sigma) {
    .Call(`_HomogeneityTest_generate_panel_data`, N, tt, beta, sigma)
}

probit_log_likelihood <- function(beta, grad, params) {
    .Call(`_HomogeneityTest_probit_log_likelihood`, beta, grad, params)
}

probit_mle <- function(X, Y, max_iter = 10000L, tol = 1e-6) {
    .Call(`_HomogeneityTest_probit_mle`, X, Y, max_iter, tol)
}

binary_individual_slopes <- function(df, max_iter = 1000L, tol = 1e-6) {
    .Call(`_HomogeneityTest_binary_individual_slopes`, df, max_iter, tol)
}

param_bootstrap_data <- function(df, beta) {
    .Call(`_HomogeneityTest_param_bootstrap_data`, df, beta)
}

boot_function <- function(df, B, null_model) {
    .Call(`_HomogeneityTest_boot_function`, df, B, null_model)
}

quantile_func <- function(vec, prob) {
    .Call(`_HomogeneityTest_quantile_func`, vec, prob)
}

bootstrap_procedure <- function(df, B, max_iter = 1000L, tol = 1e-6) {
    .Call(`_HomogeneityTest_bootstrap_procedure`, df, B, max_iter, tol)
}

